import {
  Search,
  FileHeart,
  Heart,
  MapPin,
  Menu,
  SunMoon,
  WifiOff,
  SearchX,
  ServerOff,
  Moon,
  Sun,
  CloudAlert,
  ArrowLeft,
  ThermometerSun,
  Wind,
  Droplets,
  CircleGauge,
} from 'lucide-react';

export const Icons = {
  SearchIcon: Search,
  HeartIcon: Heart,
  MenuIcon: Menu,
  LocationIcon: MapPin,
  FavoriteIcon: FileHeart,
  ThemeIcon: SunMoon,
  WifiOffIcon: WifiOff,
  SearchXIcon: SearchX,
  ServerOffIcon: ServerOff,
  MoonIcon: Moon,
  SunIcon: Sun,
  CloudIcon: CloudAlert,
  ArrowLeftIcon: ArrowLeft,
  ThermometerIcon: ThermometerSun,
  WindIcon: Wind,
  DropletsIcon: Droplets,
  CircleGaugeIcon: CircleGauge,
};
