import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Container from '@/components/container';
import { ThemeProvider } from '@/components/providers/ThemeProvider';
import ReactQueryProvider from '@/components/providers/ReactQueryProvider';
import { GlobalContextProvider } from '@/components/providers/GlobalContextProvider';
import { Toaster } from 'sonner';
import Header from '@/components/header';
import NetworkFallback from '@/components/pages/network-fallback/NetworkFallback';

const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          <ReactQueryProvider>
            <GlobalContextProvider>
              <NetworkFallback>
                <Container>
                  <Header />
                  {children}
                </Container>
              </NetworkFallback>
            </GlobalContextProvider>
          </ReactQueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
