import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Container from '@/components/container';
import Header from '@/components/header';
import NetworkFallback from '@/components/pages/network-fallback/NetworkFallback';
import AppProviders from '@/components/providers/AppProviders';

const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`}>
        <AppProviders>
          <NetworkFallback>
            <Container>
              <Header />
              {children}
            </Container>
          </NetworkFallback>
        </AppProviders>
      </body>
    </html>
  );
}
